### ISSUE TITLE
Setup basic project structure

### ISSUE THREAD

**Issue by vipulbehl** [behl-org/CRM#2]
Create a basic spring boot project with the following things

- This should be a maven spring boot project (Can be downloaded from spring boot website)
- The project should have jacoco plugin to measure code coverage (Read up on jacoco maven plugin)

Github Actions
- Setup github actions such that after every commit to master a build is triggered and all the tests are running

**Comment by Mayank-Behl** [comment]
[crm-intializr.zip](https://github.com/behl-org/CRM/files/15287175/crm-intializr.zip)

1. spring initializr used for setting up the project 
2. [Jacoco Maven plugin](https://mvnrepository.com/artifact/org.jacoco/jacoco-maven-plugin/0.8.12) used

**Comment by Mayank-Behl** [comment]
Github action is created and PR is raised.
